name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  point-to-site-with-ad-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.0.10
    with:
      working_directory: './_example/point-to-site-with-ad/'

  point-to-site-with-certificate-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.0.10
    with:
      working_directory: './_example/point-to-site-with-certificate/'

  site-to-site-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.0.10
    with:
      working_directory: './_example/site-to-site/'
